/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-05-06 09:19:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class no_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("   <nav class=\"navbar navber-default\"> <!-- ë¤ì´ê²ì´ì -->\r\n");
      out.write("      <div class=\"navbar-header\"> <!-- ë¤ì´ê²ì´ì ìë¨ ë¶ë¶ -->\r\n");
      out.write("         <!-- ë¤ì´ê²ì´ì ìë¨ ë°ì¤ ìì­ -->\r\n");
      out.write("         <button type=\"button\" class=\"navber-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navber-collapse-1\" aria-expanded=\"false\">\r\n");
      out.write("            <!-- ì´ ì¼ì¤ ë²í¼ì íë©´ì´ ì¢ìì§ë©´ ì°ì¸¡ì ëíëë¤ -->\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("         </button>\r\n");
      out.write("         <!--  ìë¨ ë°ì ì ëª©ì´ ëíëê³  í´ë¦­íë©´ ë©ì¸íì´ì§ë¡ ì´ëíë¤ -->\r\n");
      out.write("         <a class = \"navber-brand\" href=main.jsp>JSPê²ìíì¹ì¬ì´í¸</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- ê²ìí ì ëª© ì´ë¦ìì ëíëë ë©ë´ ìì­ -->\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("         <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li><a href=\"main.jsp\">ë©ì¸</a></li>\r\n");
      out.write("            <li><a href=\"bbs.jsp\">ê²ìí</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("         <!-- í¤ë ì°ì¸¡ì ëíëë ëëë¤ì´ ìì­ -->\r\n");
      out.write("         <ul class =\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li class=\"dropdown\">\r\n");
      out.write("               <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">ì ìíê¸°<span class=\"caret\"></span></a>\r\n");
      out.write("                  \r\n");
      out.write("                  <!-- ëë ë¤ì´ ìì´í ìì­ -->\r\n");
      out.write("                  <ul class=\"dropdown-menu\">\r\n");
      out.write("                     <li class=\"active\"><a href =\"login,jsp\">ë¡ê·¸ì¸ </a></li>\r\n");
      out.write("                     <li><a href=\"join.jsp\">íìê°ì</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("            </li>      \r\n");
      out.write("         </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      </nav>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
